-- Report: reports generated by a Pantheon assistant inside a panel (report library per workspace).
CREATE TABLE IF NOT EXISTS "Report" (
  "id"          TEXT NOT NULL PRIMARY KEY,
  "workspaceId" TEXT NOT NULL,
  "panel"       TEXT NOT NULL,
  "title"       TEXT NOT NULL,
  "content"     TEXT NOT NULL,
  "agentKey"    TEXT,
  "agentName"   TEXT,
  "periodLabel" TEXT,
  "createdBy"   TEXT,
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "Report_ws_panel_idx" ON "Report" ("workspaceId", "panel");
CREATE INDEX IF NOT EXISTS "Report_ws_created_idx" ON "Report" ("workspaceId", "createdAt");
